name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH (Password Authentication)
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PW }}  # Use password instead of SSH key
        command_timeout: 600s
        script: |
          cd Eventastic/backend  # Adjust to your backend directory

          # ✅ Ensure Python is Installed
          sudo apt update && sudo apt install -y python3 python3-venv

          # ✅ Create & Activate Virtual Environment
          python3 -m venv venv
          source venv/bin/activate

          # ✅ Install Python Packages in Virtual Environment
          pip install --upgrade pip
          pip install pyairbnb

          # ✅ Create .env file with GitHub Secrets
          echo "TICKETMASTER_API_KEY=${{ secrets.TICKETMASTER_API_KEY }}" > .env
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          echo "EVENTBRITE_API_KEY=${{ secrets.EVENTBRITE_API_KEY_URL }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_PW=${{ secrets.DB_PW }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env

          # ✅ Pull latest code
          git reset --hard origin/dev 
          git pull origin dev

          # ✅ Restart the backend with new environment variables
          docker-compose down
          docker-compose up -d --build
