name: Deploy to DigitalOcean

on:
  push:
    branches:
      - dev  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH (Password Authentication)
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PW }}  # Use password instead of SSH key
        command_timeout: 60m
        script: |
          cd EireLive/backend  # Adjust to your project directory

          # Create .env file with GitHub Secrets
          # echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "TICKETMASTER_API_KEY=${{ secrets.TICKETMASTER_API_KEY }}" >> .env

          cd ..

          # Pull latest code
          git pull origin dev

          # Restart the backend with new environment variables
          docker-compose down
          docker-compose up -d --build

          # Show logs to verify deployment
          docker-compose logs -f backend
        
